export * from './octicons.generated'
export { Octicon } from './octicon'
export { iconForRepository } from './repository'
export { iconForStatus } from './status'
export { syncClockwise } from './sync-clockwise'
export { stash } from './stash'
export { bitbucket } from './bitbucket'
export { desktopPlusLogo as gitBranchPlus } from './desktop-plus-logo'
export { gitlab } from './gitlab'
